services:
  - type: web
    name: weather-backend
    runtime: image
    repo: https://github.com/ialuj/weather-app
    branch: main
    buildCommand: cd weather-info-api && ./mvnw clean package
    startCommand: cd weather-info-api && java -jar target/*.jar
    envVars:
      - key: WEATHER_API_KEY
        value: wai_3abc02.e6170c5e3b2e93879e3c9d031963dcd0b40187de44a1a170
    healthCheckPath: /api/weather/health

  - type: static
    name: weather-frontend
    repo: https://github.com/ialuj/weather-app
    branch: main
    buildCommand: cd weather-info-frontend && npm install && npm run build -- --configuration production
    publishPath: weather-info-frontend/dist/weather-info-frontend/browser
    envVars:
      - key: BACKEND_URL
        value: https://weather-backend.onrender.com/api/